version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db-data_manager
    environment:
      - POSTGRES_DB=data_manager
      - POSTGRES_USER=eugene
      - POSTGRES_PASSWORD=eugene
    ports:
      - "5432:5432"
    networks:
      - my-docker-network


  manager:
    build: .
    image: manager
    container_name: manager
    ports:
      - "8086:8086"
    depends_on:
      - db
    networks:
      - my-docker-network

networks:
  my-docker-network:
    name: my-docker-network