version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db-user_provider
    environment:
      - POSTGRES_DB=user_provider
      - POSTGRES_USER=eugene
      - POSTGRES_PASSWORD=eugene
    ports:
      - "5432:5432"
    networks:
      - my-docker-network


  server:
    build: .
    image: server-image
    container_name: server-container
    ports:
      - "8085:8080"
    depends_on:
      - db
    networks:
      - my-docker-network

networks:
  my-docker-network:
    name: my-docker-network